name: audio_tagger

channels:
  - pytorch
  - nwani
  - defaults
  - conda-forge

dependencies:
  - python=3.6.7
  - requests=2.21.0
  - flask=1.0.2
  - portaudio=19.6.0
  - pyaudio=0.2.11
  - kivy=1.10.1
  - pytorch=1.0.1
  - torchvision=0.1.8


  - pip:
    - madmom==0.16.1
    - matplotlib==3.0.3
    - opencv_python==4.1.0.25